name: Build/release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 20.x

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.github_token }}
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
          include_files: |
            *.zip
            *.AppImage
            *.exe
            *.dmg
            *.rpm
            *.deb

      - name: Get tag name
        id: tag_name
        run: echo ::set-output name=TAG_NAME::${GITHUB_REF#refs/tags/}

      - name: Create release draft
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.github_token }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${GITHUB_REPOSITORY}/releases \
            -d '{"tag_name": "${{ steps.tag_name.outputs.TAG_NAME }}", "name": "Release ${{ steps.tag_name.outputs.TAG_NAME }}", "draft": true, "prerelease": false}'
